### ISSUE TITLE
Hardware requirements?

### ISSUE THREAD

**Issue by XiHuYan** [PeterZZQ/scMoMaT#2]
Hi, when I run demo_scmomat.ipynb on a Linux server with 260G+ memory and one 3090 GPU, I found that when step 2 (trainning scMoMaT) was done, ~130G of memory was used and step 3 (post-processing) caused a memory overflow. 

Could you explain the hardware environment required to run scmomat?

**Comment by PeterZZQ** [comment]
Hello, the sample data in the demo is quite large to start with. The data includes 76,000 cells. Loading the RNA and especially the ATAC count matrices (around 25,000 features) should already consume a lot of memory to start with. We will update the code later to reduce the data size.

Our server has 504G memory, and the training takes around 50G memory. Our GPU is A40 with 48G memory, the training consumes 6G GPU memory. However, the post-processing step indeed consumes a lot of memory as it needs to calculate and save pair-wise distance between cells. The distance matrix can be quite large when the number of cells is too large, which can cause memory overflow if you don't have enough memory. 

For such a large dataset, it is also not a good idea to run with jupyter notebook. When we did the testing, we trained the model using a Python script first and save the trained model and all factor values. We load the value whenever the analysis is needed. If you are using the sample data simply to validate the method, I would highly suggest you downsample the dataset first. 

There are also other parameters that can control the resources and time consumption, e.g. batch_size, n_jobs, training iteration, etc. Including the following command at the beginning of the script can constrain the CPU consumption of the whole training procedure:

```python
import sys, os
# constrain numpy core usage to be only 1
os.environ["OMP_NUM_THREADS"] = "1"
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['NUMEXPR_NUM_THREADS'] = '1'
import numpy as np
 
# constrain pytorch core usage to be only 1
import torch


torch.set_num_threads(1)
```

**Comment by XiHuYan** [comment]
Thanks for your detailed reply!

If I want to test scmomat on a large-scale diagonal dataset (like 500k cells for scRNA and 600K cells for scATAC), can I skip the post-processing and retraining procedures to reduce memory consumption? If skipping the post-processing and retraining, will scmomat's performance drop significantly?

**Comment by PeterZZQ** [comment]
Yes, you don't always need to do post-processing, it depends on the strength of batch effect between count matrices. You can try without post-processing step first.

**Comment by XiHuYan** [comment]
Hi, I updated scmomat to the lastest version 0.2.0 and tried to run the demo_scmomat. It reported memory overflow again ...
I found this is because of converting `pair_dist` to sparse matrix in [utils.py](https://github.com/PeterZZQ/scMoMaT/blob/212d7f253d833690ec1ff3ede60a691191a4deda/scmomat/utils.py#L763). Maybe `pair_dist` is not sparse at all, thus converting it into sparse format will greatly increase memory consumption. If I skipped this conversion and rerun the demo, it finished normally. 
Maybe you should judge whether `pair_dist` is sparse enough before converting it to sparse matrix.

**Comment by PeterZZQ** [comment]
Hi, the `pair_dist` has to be sparse to trigger the post-processing step. If you use dense `pair_dist`, it will show 
```
standard mode, recalculate knn...
```
The pre-calculated distance matrix is not used, and the algorithm falls back to use the standard UMAP procedure. Instead, the successful procedure should show 
```
using precompute
```
We are still investigating the issue, and will let you know if there is an alternative way to solve the memory issue.

**Comment by PeterZZQ** [comment]
Hi,

We have updated the newest version of scMoMaT to solve the post-processing issue. Please check the [demo post-processing](https://github.com/PeterZZQ/scMoMaT/blob/main/demo_scmomat.ipynb) for the update. In the update, we no longer calculate the pair_dist, which solves the memory issue of the original calculation.

The newest post-processing procedure follows:
```
zs = model.extract_cell_factors()

n_neighbors = 100
r = None
knn_indices, knn_dists = scmomat.calc_post_graph(zs, n_neighbors, njobs = 8, r = r)
x_umap = scmomat.calc_umap_embedding(knn_indices = knn_indices, knn_dists = knn_dists, n_components = 2, n_neighbors = n_neighbors, min_dist = 0.20, random_state = 0)
```
