### ISSUE TITLE
How to simulate the ADT in multimodal data.

### ISSUE THREAD

**Issue by DSichang** [PeterZZQ/scMoMaT#3]
Hi developers,

I am wondering if you could share the code used for simulating the ADT in multimodal data. Since the RNA and ATAC data were simulated using scDart, I am interested in how to simulate ADT as well.

Thank you!

**Comment by PeterZZQ** [comment]
Hi, 

We have added the simulation scripts to the repo: https://github.com/PeterZZQ/scMoMaT/tree/main/symsim_scripts
